language: rust
cache: cargo
sudo: false

matrix:
  include:

  - rust: stable
    script:
    - cargo build --feature s3
    - cargo build --feature local
    - cargo test
    - rustup component add clippy
    - cargo clippy --feature s3
    - cargo clippy --feature local
    - rustup component add rustfmt
    - cargo fmt --all -- --check
    env: RUST_BACKTRACE=1

notifications:
  email:
    on_success: never
