language: rust
cache: cargo
sudo: false

matrix:
  include:

  - rust: stable
    script:
    - cargo build --all
    - cargo test --all
    - rustup component add clippy
    - cargo clippy
    - rustup component add rustfmt
    - cargo fmt --all -- --check
    env: RUST_BACKTRACE=1

notifications:
  email:
    on_success: never
